### ISSUE TITLE
[Oops.] Type error for production rule for CFG

### ISSUE THREAD

**Issue by plin25** [jeffgerickson/algorithms-ftw#177]
**Chapter number or note title:** Models of Computation Lecture 5: Context-Free Languages and Grammars 

**Page number:** 1

**Error description:** The third bullet explaining CFG states
- A finite set R of production rules of the form A → w, where A ∈ Γ is a non-terminal and w ∈ (Σ ∪ Γ)* is a string of symbols and variables.

which does not include the possibility of w = ε, as seen a few lines later in the example production rule C → ε

**Suggested fix (if any):** Replace w ∈ (Σ ∪ Γ)* with w ∈ (Σ ∪ Γ)* ∪ {ε}

**Comment by echuber2** [comment]
Couldn't (Σ ∪ Γ)* already imply ε because of the Kleene star?

**Comment by plin25** [comment]
I'm an idiot
