### ISSUE TITLE
[Oops.]

### ISSUE THREAD

**Issue by wn** [jeffgerickson/algorithms-ftw#190]
**Please verify that the error is present in the most recent revision before reporting.**

**Chapter number or note title:** [8.2]

**Page number:** [275]

**Error description:** 
["Negative edges are a thorn in the side of most shortest-path problems, because the presence of a negative cycle might imply that shortest paths may not
be well-defiend."]

**Suggested fix (if any):** 
["Negative edges are a thorn in the side of most shortest-path problems because the presence of a negative cycle might imply that shortest paths may not
be well-defined."]

**Comment by schra** [comment]
@wn Why did you close this issue? I downloaded the pdf a couple of days ago and the typo is still there. Could you maybe re-open this issue?
